### ISSUE TITLE
Bulk sync on bazarr

### ISSUE THREAD

**Issue by modem7** [ajmandourah/bazarr-sync#1]
Heya, 

Just an FYI, 

There is a bulk sync (albeit, per show) on Bazarr. 

![image](https://github.com/ajmandourah/bazarr-sync/assets/4349962/08925faf-13d8-4f9d-a9fe-4974efdc13a7)

The readme may need to be updated just in case this crops up again as a question.

**Comment by ajmandourah** [comment]
I become aware of this yesterday. Thanks for mentioning it. will do

**Comment by modem7** [comment]
I'll close the ticket as it was mostly just an fyi.

Cheers!
