### ISSUE TITLE
unable to install on debian 12

### ISSUE THREAD

**Issue by madejackson** [ajmandourah/bazarr-sync#2]
Hi, I'm unable to install this on debian 12.

bazarr-sync is never recognized as a command.

When I restart the shell, go is gone as well.

**Comment by ajmandourah** [comment]
It seems like you have installed it via go. One quirk with go is your gopath needed to be added in your PATH variable.

Check this out
https://go.dev/wiki/SettingGOPATH#bash
I will add this to the Readme as well
Lemme know if it worked.
