### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Secret1553** [ajmandourah/bazarr-sync#4]
![ERROR](https://github.com/ajmandourah/bazarr-sync/assets/173389956/abc24232-8522-474e-ab99-7874e2c17b90)

Had an error with a sync and then it keeps retrying and it messed up the terminal.

![Animation](https://github.com/ajmandourah/bazarr-sync/assets/173389956/fbf30748-229d-4230-8b33-18281fb7b2de)

its still going I think

**Comment by ajmandourah** [comment]
Hey, this is odd. Is it a recurrent issue with other files or with this specific show?

**Comment by Secret1553** [comment]
Only happened once, I had a audio folder with other languages in the movie folder.  Maybe that was the issue.

**Comment by ajmandourah** [comment]
probably. although it should not be. I failed to reproduce the error. it could be also bazarr related if bazarr got confused somehow. please open a new issue of the problem persisted. Thanks
