### ISSUE TITLE
error, i can't run on docker

### ISSUE THREAD

**Issue by sorinpetrus3** [ajmandourah/bazarr-sync#5]
Hi, i try to run this but i get an error

Using config file: /usr/src/app/config.yaml
Connection Error:  Get "https://192.168.1.200:6767/api/system/status": dial tcp 192.168.1.200:6767: i/o timeout
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x7ff618]

goroutine 1 [running]:
github.com/ajmandourah/bazarr-sync/internal/bazarr.HealthCheck({{0xc000130da0, 0xd}, {0xc000130e88, 0x4}, {0xc000130e00, 0x5}, {0xc000154880, 0x20}, {0xc000154920, 0x1b}, ...})
        /usr/src/app/internal/bazarr/bazarr.go:156 +0x178
github.com/ajmandourah/bazarr-sync/internal/cli.init.func2(0xc0001b2300?, {0x8d9040?, 0x4?, 0x8d9044?})
        /usr/src/app/internal/cli/shows.go:30 +0x7c
github.com/spf13/cobra.(*Command).execute(0xce7840, {0xd4f080, 0x0, 0x0})
        /go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:987 +0xab1
github.com/spf13/cobra.(*Command).ExecuteC(0xce7560)
        /go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039
github.com/ajmandourah/bazarr-sync/internal/cli.Execute()
        /usr/src/app/internal/cli/root.go:34 +0x1a
main.main()
        /usr/src/app/cmd/bazarr-sync/main.go:8 +0xf

 please help me how to solve this ?

**Comment by ajmandourah** [comment]
Hi
Is bazarr running on https? 
make sure the address and the port are correct also. additionally from bazarr setting make sure you have your api key added correctly

**Comment by sorinpetrus3** [comment]
Hi and thanks for your response
No the bazar is running on http not in https,  I don't  know how to run on https locally  i have a https address but is behind of traefik for internet access and i try this one and still no work.

**Comment by ajmandourah** [comment]
Well the logs mention that you have set the protocol to https. Try changing it to http and give it a try

**Comment by sorinpetrus3** [comment]
yes, that was the problem. thank you very much for your help

**Comment by ajmandourah** [comment]
Nice
Have fun. Will close this as complete
