### ISSUE TITLE
unable to install on debian 12

### ISSUE THREAD

**Issue by madejackson** [ajmandourah/bazarr-sync#7]
Hey, I'm coming again.

Still not working on debian 12, despite go installed:
![image](https://github.com/user-attachments/assets/fa968e6a-1a5c-4a9a-9217-f3832df86d65)

**Comment by ajmandourah** [comment]
can you check
```
ls /usr/local/go/bin
```

**Comment by madejackson** [comment]
Yes, here you go:

![image](https://github.com/user-attachments/assets/a7104091-7adc-4191-91c1-f8f9e03ef391)

**Comment by ajmandourah** [comment]
This is strange.
How did you install golang?
Do you have a go folder on your home folder? If so does it have the binary inside?

**Comment by madejackson** [comment]
Oh, I found the solution thanks to your question. Now the other expected issue though. Let's see if I can fix that.

![image](https://github.com/user-attachments/assets/77233e48-c3db-47c4-b23d-fc06938857ed)

**Comment by ajmandourah** [comment]
Yeah as I expected
Go creates a go folder on the home dir where installed bin lives to separate them from the usr bin. You need to add these yo path if you want to call it directly.
Make sure bazarr is reachable though.
