### ISSUE TITLE
Can't reach bazarr when it is behind a reverse proxy

### ISSUE THREAD

**Issue by jaum20** [ajmandourah/bazarr-sync#8]
At home, I access bazarr through the url `https://192.168.15.73/bazarr` . In my config.yaml I have the `Port` empty, but bazarr-sync will add an `:` to the url.: `https://192.168.15.73/bazarr:/api/system/status`

If I put `443` there, it becomes: `https://192.168.15.73/bazarr:443/api/system/status`

**Comment by ajmandourah** [comment]
Hi. You are correct, I have not take in mind the subpath reverse proxy.
For now you need to direct bazarr-sync to the address of the container / bazarr.
I will work on adding this in the upcoming days

**Comment by ajmandourah** [comment]
This should now be fixed. please give it a test
